In [2]:
import numpy as np

In [3]:
# How to create Numpy
#1) np.array
a=np.array([1,2,3,4,5,6])
print(a)
print(type(a))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
# 2D and 3D array
b=np.array([[1,2,3],[4,5,6]])
print(b)

c=np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]]


In [7]:
# dtype---Datatype
a=np.array([1,2,3],dtype=float)
print(a)
b=np.array([1,2,3],dtype=complex)
print(b)

[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [12]:
# np.arange
a=np.arange(1,14)
print(a)
b=np.arange(0,14,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  2  4  6  8 10 12]


In [19]:
# with reshape--convert into rows and columns
# reshpe is used only when products of two nos is same as end index
a=np.arange(1,11).reshape(5,2)
print(a)
b=np.arange(1,21).reshape(2,10)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [6]:
#np.ones and np.zeroes  ----used to initialized fastly.
a=np.ones((4,5))
print(a)
b=np.zeros((2,4))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#np.random ----used to generate random numbers between 0 to 1
np.random.random((2,3))


array([[0.40831499, 0.59903823, 0.98970234],
       [0.55335878, 0.53317609, 0.08813069]])

In [8]:
#np.linspace--used to generate linearly seperable points
np.linspace(-1,10,5)

array([-1.  ,  1.75,  4.5 ,  7.25, 10.  ])

In [10]:
#np.identity--used to generate identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Numpy attributes
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [16]:
#1) ndim attribute
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [17]:
#2) shape--gives no. of rows and columns
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [19]:
#3) size--- gives no of items
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [21]:
#4)itemsize--gives item size
print(a1.itemsize)
print(a2.itemsize)
print(a2.itemsize)

4
8
8


In [23]:
#5) dtype---gives data type
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [25]:
#How to change datatype
# astype is used to change datatype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
# Array Operations

a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [28]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [31]:
# scalar operations(+,-,*,%,/,**)
print(a1+2)
print(a2*2)
print(a1%2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [35]:
# relational operators---checks with every elements
print(a2>15)
print(a1==0)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True False False False]
 [False False False False]
 [False False False False]]


In [38]:
# vector operations(+,-,*,%,/,**)(between two arrays)
print(a1+a2)
print(a2**a1)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[         1         13        196       3375]
 [     65536    1419857   34012224  893871739]
 [-169803776 -288903179 -154967040 1328067399]]


In [40]:
# Array Functions
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[64., 88.,  6.],
       [11., 96., 73.],
       [72., 38., 39.]])

In [42]:
#1) max--gives maximum item in the array
#2) min--gives manimum item in the array
#3) sum--gives sum of item in the array
#4) prod--gives product item in the array
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

96.0
6.0
487.0
277959405993984.0


In [50]:
# min,max,sum,prod of array column wise(axis=0,1)
# 0-->column ,1-->row
print(np.max(a1,axis=0))  #column
print(np.max(a1,axis=1))  #row

[72. 96. 73.]
[88. 96. 72.]


In [55]:
# Statistical Functions--mean,median,std,var
print(np.mean(a1,axis=0))
print(np.median(a1,axis=0))
print(np.std(a1,axis=0))
print(np.var(a1,axis=0))

[49.         74.         39.33333333]
[64. 88. 39.]
[27.06781607 25.66450207 27.35365099]
[732.66666667 658.66666667 748.22222222]


In [56]:
# trigonometric functions
np.sin(a1)

array([[ 0.92002604,  0.0353983 , -0.2794155 ],
       [-0.99999021,  0.98358775, -0.67677196],
       [ 0.25382336,  0.29636858,  0.96379539]])

In [58]:
# dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [62]:
# log and exponents
print(np.log(a1))
print(np.exp(a1))

[[4.15888308 4.47733681 1.79175947]
 [2.39789527 4.56434819 4.29045944]
 [4.27666612 3.63758616 3.66356165]]
[[6.23514908e+27 1.65163625e+38 4.03428793e+02]
 [5.98741417e+04 4.92345829e+41 5.05239363e+31]
 [1.85867175e+31 3.18559318e+16 8.65934004e+16]]


In [72]:
# round,floor,ceil
a=np.arange(10,dtype=float)
print(a)
print(np.round(a*100))
print(np.floor(a*100))
print(np.ceil(a*100))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[  0. 100. 200. 300. 400. 500. 600. 700. 800. 900.]
[  0. 100. 200. 300. 400. 500. 600. 700. 800. 900.]
[  0. 100. 200. 300. 400. 500. 600. 700. 800. 900.]


In [82]:
# Indexing and Slicing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [86]:
#Indexing
print(a1)
print(a1[0])
print(a1[-1])

[0 1 2 3 4 5 6 7 8 9]
0
9


In [90]:
print(a2)
print(a2[0,2])
print(a2[1,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
7


In [94]:
print(a3)
print(a3[1,0,0])
print(a3[1,1,0])


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
4
6


In [96]:
# Slicing
print(a1)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4.]


In [140]:
print(a2)
print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3])
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[-2:2,::3])
print(a2[1,::3])
print(a2[0:2,1:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[4 7]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [178]:
a3=np.arange(27).reshape(3,3,3)
print(a3)
print(a3[1])
print(a3[::2])
print(a3[0,1,:])
print(a3[1,:,1])
print(a3[2,1:3,1:3])
print(a3[::2,0,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [182]:
# Iterating
print(a1)
for i in a1:
    print(i)


[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [185]:
print(a2)
for i in a2:
    print(i)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [187]:
print(a3)
for i in a3:
    print(i)
for i in np.nditer(a3):  # to give each element
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [192]:
# Transpose- convert rows into columns and columns into rows
print(a2)
print(np.transpose(a2))  #first syntax
print(a2.T)              # second syntax

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [195]:
# ravel --convert any dimension of array into one dimension
print(a2)
print(a2.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [198]:
#Stacking ---joining two arrays either horizontally(horizontal stacking) or vertical(vertical stacking)
#condition shape should be same
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
print(np.hstack((a4,a5)))   #horizontal stacking
print(np.vstack((a4,a5)))   #vertical stacking

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [206]:
#Splitting---split into equal arrays
#horizontal spliting
print(np.hsplit(a4,2))
#verical splitting
print(np.vsplit(a4,3))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
