In [2]:
import numpy as np

In [3]:
#np.sort
a=np.random.randint(1,100,15)
b=np.random.randint(1,100,24).reshape(6,4)
print(a)
print(b)

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
[[66 76 81  3]
 [62 46 22 31]
 [75 91 71 43]
 [92 37 36 97]
 [93 81 72 52]
 [16 78 36 51]]


In [4]:
np.sort(a)  #ascending sort

array([ 9,  9, 18, 23, 34, 35, 45, 50, 53, 61, 63, 73, 85, 85, 90])

In [5]:
np.sort(a)[::-1]  #descending sort

array([90, 85, 85, 73, 63, 61, 53, 50, 45, 35, 34, 23, 18,  9,  9])

In [6]:
np.sort(b) #rowise sorting

array([[ 3, 66, 76, 81],
       [22, 31, 46, 62],
       [43, 71, 75, 91],
       [36, 37, 92, 97],
       [52, 72, 81, 93],
       [16, 36, 51, 78]])

In [8]:
np.sort(b,axis=0) #column sorting

array([[16, 37, 22,  3],
       [62, 46, 36, 31],
       [66, 76, 36, 43],
       [75, 78, 71, 51],
       [92, 81, 72, 52],
       [93, 91, 81, 97]])

In [9]:
#np.append-append values at the end of the array
np.append(a,200)

array([ 90,  18,  63,  85,  35,  53,  34,  23,  61,   9,  50,   9,  85,
        45,  73, 200])

In [10]:
 b

array([[66, 76, 81,  3],
       [62, 46, 22, 31],
       [75, 91, 71, 43],
       [92, 37, 36, 97],
       [93, 81, 72, 52],
       [16, 78, 36, 51]])

In [12]:
np.append(b,np.ones((b.shape[0],1)),axis=1) #append columns

array([[66., 76., 81.,  3.,  1.],
       [62., 46., 22., 31.,  1.],
       [75., 91., 71., 43.,  1.],
       [92., 37., 36., 97.,  1.],
       [93., 81., 72., 52.,  1.],
       [16., 78., 36., 51.,  1.]])

In [13]:
#np.concatenate()--concatenate a sequence of arrays along an existing axis
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
print(np.concatenate((c,d),axis=0)) # concatenate rowise
print(np.concatenate((c,d),axis=1)) # concatenate columnwise

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [21]:
#np.unique--we can get hte unique valuesfrom an array as parameter in np.unique() method.
e=np.array([11,1,1,2,3,4,5,8,5,6,7])
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11])

In [30]:
#np.expand_dims---we can get the expanded dimension of an array
print(a)
print(a.shape)
b=np.expand_dims(a,axis=0)
print(b)
print(b.shape)
b=np.expand_dims(a,axis=1)
print(b)

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
(15,)
[[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]]
(1, 15)
[[90]
 [18]
 [63]
 [85]
 [35]
 [53]
 [34]
 [23]
 [61]
 [ 9]
 [50]
 [ 9]
 [85]
 [45]
 [73]]


In [31]:
#np.where()-returns the indices of elements in an input array where the given condition is satisfied.
print(a)
np.where(a>50)

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]


(array([ 0,  2,  3,  5,  8, 12, 14], dtype=int64),)

In [33]:
#np.where() Syntax-------np.where(consition,true,false)
#replace all values >50 with 0
print(np.where(a>50,0,a))
print(np.where(a%2==0,0,a))


[ 0 18  0  0 35  0 34 23  0  9 50  9  0 45  0]
[ 0  0 63 85 35 53  0 23 61  9  0  9 85 45 73]


In [45]:
#np.argmax()--returns indices of the max element of the array in a particular axis
print(a)
print(np.argmax(a))
c=np.random.randint(1,100,25).reshape(5,5)
print(c)
print(np.argmax(c,axis=1)) #row wise
print(np.argmax(c,axis=0)) #column wise

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
0
[[18 15 33 68 25]
 [58 63 43 39  2]
 [79 75 84 62  1]
 [95 82 43  5 36]
 [ 7 32 95 35 92]]
[3 1 2 0 2]
[3 3 4 0 4]


In [46]:
#np.argmin()--returns indices of the min element of the array in a particular axis
print(a)
print(np.argmin(a))
c=np.random.randint(1,100,25).reshape(5,5)
print(c)
print(np.argmin(c,axis=1)) #row wise
print(np.argmin(c,axis=0)) #column wise

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
9
[[28 94 77 86 67]
 [66 56 50 87 84]
 [53 24  2 64 67]
 [23 87 56 68 85]
 [66 54 36 61 74]]
[0 2 2 0 2]
[3 2 2 4 0]


In [51]:
#np.cumsum()--mean cummulative sum
# this function used to cumulative sum of array elements over a given axis
print(a)
np.cumsum(a)
print(c)
print(np.cumsum(c,axis=0)) #column wise
print(np.cumsum(c,axis=1)) #row wise

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
[[28 94 77 86 67]
 [66 56 50 87 84]
 [53 24  2 64 67]
 [23 87 56 68 85]
 [66 54 36 61 74]]
[[ 28  94  77  86  67]
 [ 94 150 127 173 151]
 [147 174 129 237 218]
 [170 261 185 305 303]
 [236 315 221 366 377]]
[[ 28 122 199 285 352]
 [ 66 122 172 259 343]
 [ 53  77  79 143 210]
 [ 23 110 166 234 319]
 [ 66 120 156 217 291]]


In [53]:
#np.cumprod()-- gives cumulative product
print(a)
np.cumprod(a)

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]


array([         90,        1620,      102060,     8675100,   303628500,
       -1087558684,  1677710408,   -67366280,   185624216,  1670617944,
        1926518576,   158798000,   612928112,  1811961264,  -870813904])

In [59]:
#np.percentile()--compute the nth percentile of the given data along specified axis
print(a)
print(np.percentile(a,0))
print(np.percentile(a,50))
print(np.percentile(a,100))
print(np.percentile(a,75))

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
9.0
50.0
90.0
68.0


In [63]:
#np.histogram()--built in function which represents the frequency of data distribution in the graphical form.
print(a)
print(np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100]))
print(np.histogram(a,bins=[0,50,100]))

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
(array([2, 1, 1, 2, 1, 2, 2, 1, 2, 1], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))
(array([7, 8], dtype=int64), array([  0,  50, 100]))


In [65]:
#np.corrcoef()--return person product-moment correlation coefficients
salary=np.array([2000,4000,6000,5600,4200])
experience=np.array([1,2,4,1,2])
np.corrcoef(salary,experience)

array([[1.        , 0.56940578],
       [0.56940578, 1.        ]])

In [68]:
#np.isin()--we can see that one array having values are checked in a different numpy array having different elements with different sizes
print(a)
items=[10,20,40,50,90,100]
np.isin(a,items)
print(a[np.isin(a,items)])

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
[90 50]


In [72]:
#np.flip()---reverses the order of array elements along the specified axis,preserving the shape of the array.
print(a)
print(np.flip(a))
print(c)
print(np.flip(c,axis=0))  #column wise

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]
[73 45 85  9 50  9 61 23 34 53 35 85 63 18 90]
[[28 94 77 86 67]
 [66 56 50 87 84]
 [53 24  2 64 67]
 [23 87 56 68 85]
 [66 54 36 61 74]]
[[66 54 36 61 74]
 [23 87 56 68 85]
 [53 24  2 64 67]
 [66 56 50 87 84]
 [28 94 77 86 67]]


In [76]:
#np.put()--replaces specific elements of an array with given values .
d=np.array([1,2,3,4,5,6,78,9])
print(d)
print(np.put(d,[0,2],[111,22]))#np.put changes elements permenantly in the original array

[ 1  2  3  4  5  6 78  9]
None


In [77]:
print(d)

[111   2  22   4   5   6  78   9]


In [79]:
#np.delete()--returns new array with the deletion of the array elements
print(d)
np.delete(d,[1,4])

[111   2  22   4   5   6  78   9]


array([111,  22,   4,   6,  78,   9])

In [85]:
#Set fuctions
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
print(np.union1d(m,n))
print(np.intersect1d(m,n))
print(np.setdiff1d(m,n))
print(np.setxor1d(m,n))
print(np.in1d(m,3))

[1 2 3 4 5 6 7]
[3 4 5]
[1 2]
[1 2 6 7]
[False False  True False False]


In [87]:
#np.clip() --used to clip(limit) the values in an array
print(a)
np.clip(a,a_min=25,a_max=75)

[90 18 63 85 35 53 34 23 61  9 50  9 85 45 73]


array([75, 25, 63, 75, 35, 53, 34, 25, 61, 25, 50, 25, 75, 45, 73])